### ISSUE TITLE
Node.js Security Checklist

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/I-Talent#836]
# Node.js Security Checklist
This is a checklist to secure Node.js application, Please implement each item and leave a description.

## Useful links:
- https://blog.risingstack.com/node-js-security-checklist/
- https://medium.com/swlh/3-security-pitfalls-every-react-developer-should-know-c04715b876b5
- https://www.simform.com/react-security-vulnerabilities-solutions/
- https://expressjs.com/en/advanced/best-practice-security.html

### Security HTTP Headers
we should use `Helmet` to set our headers https://www.npmjs.com/package/helmet for backend
https://www.twilio.com/blog/2017/11/securing-your-express-app.html

- [x] **Strict-Transport-Security enforces secure (HTTP over SSL/TLS) connections to the server**
Description: implemented for backend

- [x] **X-Frame-Options provides clickjacking protection**
Description: implemented for backend

- [x] **X-XSS-Protection enables the Cross-site scripting (XSS) filter built into most recent web browsers**
Description: implemented for backend

- [x] **X-Content-Type-Options prevents browsers from MIME-sniffing a response away from the declared content-type**
Description: implemented for backend

- [x] **Content-Security-Policy prevents a wide range of attacks, including Cross-site scripting and other cross-site injections**
Description: implemented for backend

- [ ] **HTTP/2**
Description:

### Authentication
- [x] **Authentication is handled by keycloak for our application.**

#### Cookie Flags
- [x] **Secure**: this attribute tells the browser to only send the cookie if the request is being sent over HTTPS.
Description:

- [x] **HttpOnly**: this attribute is used to help prevent attacks such as cross-site scripting, since it does not allow the cookie to be accessed via JavaScript.
Description:

#### Cookie Scope
- [x] **domain** :  this attribute is used to compare against the domain of the server in which the URL is being requested. If the domain matches or if it is a sub-domain, then the path attribute will be checked next.
Description:

- [x] **path**:  in addition to the domain, the URL path that the cookie is valid for can be specified. If the domain and path match, then the cookie will be sent in the request.
Description:

- [x] **expires** :  this attribute is used to set persistent cookies, since the cookie does not expire until the set date is exceeded.
Description:

#### CSRF
- [ ] **CSRF Token**
Description:

### Data Validation
- [ ] **XSS**:  filter/sanitize user input
Description:

- [x] **SQL Injection**:  filter/sanitize user input
Description: Prisma protects against SQL injection
https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/raw-database-access#sql-injection

- [ ] **Command Injection**:  filter/sanitize user input
Description:

### Secure Transmission
- [ ] **SSL Version, Algorithms, Key length**:  ciphers, keys and renegotiation is properly configured. certificate validity.
Description:

- [x] **HSTS**:  - Strict-Transport-Security header enforces secure (HTTP over SSL/TLS) connections to the server.
Description: This is enforced by openshift. All connections are HTTPS.

### Secure Transmission
- [x] **Account Lockout**:  In practice it means that after a small number of unsuccessful login attempts the systems prohibits login attempts for a given period.
Description:

- [ ] **Regular Expression**:  This kind of attack exploits the fact that most Regular Expression implementations may reach extreme situations that cause them to work very slowly. (Regular expression Denial of Service - ReDoS)
Description:

### Error Handling
- [ ] **Error Codes, Stack Traces**:  During different error scenarios the application may leak sensitive details about the underlying infrastructure, like: X-Powered-By:Express.
Description:

### NPM
- [x] **Node Security**:  NPM has lots of packages what you can use instantly, but that comes with a cost: you should check what you are requiring to your applications. They may contain security issues that are critical.
Description:
